= Внутри командное code review

После создания PR автор добавляет проверяющих.

*Временной предел:* PR должен находится в стадии ревью не более 14 часов.

*Количество approve'ов:*

- по количеству человек в команде, за исключением автора PR (т.е. при 5 разработчиках - 4 approve'а)
- в критических ситуациях 2 (если у кого-то форс-мажор и он никак не сможет проверить) и делается `force merge`.

== Чек-лист ревьюера:

- Ознакомиться и понять цель и суть задачи.
- Общая структура. Как код вписывается в проект.
- Реализация, функциональность. Способен ли код полностью удовлетворить поставленные задачи.
- Проверить мелкие детали (имена функций и переменных и т.д.)
- Удобство. Интуитивность UI и соответствие его общему стилю.
- Многопоточность. Рецензируемый код не должен конфликтовать с другими элементами кодовой базы при многопоточном выполнении. То же касается и внутренних конфликтов кода.
- Простота. Код не должен быть слишком громоздким. Максимально упрощаем, но не в ущерб качеству и функциональности.
- Перспектива масштабирования. Возможно, в коде могут быть реализованы некоторые возможности, востребованные в будущем.
- Наличие тестов (модульные, интеграционные и так далее). Внимательно изучите их структуру.
- Преемственность разработчиков. Все переменные, поля, функции, вообще все объекты и элементы в коде должны иметь ясные, однозначные имена. Комментарии к коду ясно и чётко объясняют, зачем нужен каждый элемент. Обратите внимание, вопрос «зачем это» важнее вопроса «что это».
- Соответствие стандартам. Код должен соответствовать стандарту стиля и быть должным образом документирован.

Если что-то из этого не устроит или обнаружена ошибка - оставить комментарий. Ожидается исправление (если ошибка\ комментарий очевидны) или обсуждение.

== Типы замечаний и ожидаемые действия от автора, в зависимости от типа.

- `critical` - переделать по аргументированному комментарию ревьюера (со ссылкой на code style, например)
- `major` - нужен рефакторинг, но на данный момент ок.
- `minor` - хорошая идея на будущее.

== Аргументы для критических замечаний:
- Наличие ошибок и/или уязвимостей в коде.
- Нарушение функциональных требований/бизнес-логики.
- Не может быть скомпилировано, задеплоено, не проходит обязательные автоматические тесты.
- Драматически ухудшает производительность.
- Алгоритм можно упростить и в конкретной ситуации это важно.

