= Требования к данным


|===
|Элемент данных |Описание|Структура данных или тип|Длина|Значения


s|Сотрудник
s|Сводные данные о сотруднике компании
s|идентификатор

+ электронная почта

+ 1: многие {телефон}

+ фамилия

+ имя

+ отчество

+ должность

+ отдел компании

+ дата рождения

+ место рождения

+ пол

+ 0: многие {иностранный язык}

+ грейд

+ модель работы

+ СНИЛС

+ ИНН

+ гражданство

+ адрес регистрации

+ адрес проживания

+ воинский учет

+ 1: многие {паспорт}

+ разрешение на работу

+ 0: многие {отпуск}

+ 0: многие {скан документа}

+ 1: многие {трудовой договор}

+ передвижение по должностям

+ финансы
|
|

s|Сотрудник (кратко)
s|Краткий вариант данных о сотруднике компании
s|идентификатор

+ фамилия

+ имя

+ отчество

+ должность

+ отдел компании

+ электронная почта

+ 1: многие {телефон}
|
|

e|Идентификатор сотрудника
e|Уникальный идентификатор, назначаемый системой каждому новому сотруднику
e|Целое
e|10
|

e|Электронная почта сотрудника
e|Электронная почта сотрудника
e|Буквенно-числовое значение
e|50
|

e|Телефон сотрудника
e|Телефон сотрудника
e|Числовое значение
e|15
|

e|Фамилия сотрудника
e|Фамилия сотрудника
e|Буквенное значение
e|150
|

e|Имя сотрудника
e|Имя сотрудника
e|Буквенное значение
e|150
|

e|Отчество сотрудника
e|Отчество сотрудника
e|Буквенное значение
e|150
|

e|Должность сотрудника
e|Должность сотрудника
e|Буквенно-числовое значение
e|150
|

e|Отдел сотрудника
e|Отдел, к которому принадлежит сотрудник
e|Буквенно-числовое значение
e|150
|

e|Дата рождения сотрудника
e|Дата рождения сотрудника
e|Дата согласно RFC 3339
e|10
|

e|Место рождения сотрудника
e|Место рождения сотрудника
e|Буквенное значение
e|150
|

e|Пол сотрудника
e|Пол сотрудника
e|Буквенное значение
|
e|женский, мужской

e|Иностранный язык
e|Название иностранного языка, который знает сотрудник
e|Буквенное значение
e|150
|

e|Грейд сотрудника
e|Грейд сотрудника
e|Буквенно-числовое значение
e|1
|

e|Модель работы сотрудника
e|Модель работы сотрудника
e|Буквенное значение
|
e|в офисе, удаленная, гибридная

s|Финансы сотрудника
s|Сводные данные о финансах сотрудника
s|Оклад

+ налоговые выплаты

+ социальный выплаты
|
|

e|Оклад
e|Оклад сотрудника, указанный в минимальной денежной единице
e|Целое
e|18
|

e|Налоговые выплаты
e|Налоговые выплаты сотрудника, указанные в минимальной денежной единице
e|Целое
e|18
|

e|Социальные выплаты
e|Социальные выплаты сотрудника, указанные в минимальной денежной единице
e|Целое
e|18
|

e|СНИЛС сотрудника
e|СНИЛС (номер страхования) сотрудника
e|Числовое значение
e|11
|

e|ИНН сотрудника
e|ИНН (налоговый номер) сотрудника
e|Числовое значение
e|12
|

e|Гражданство сотрудника
e|Гражданство сотрудника
e|Буквенное значение
e|150
|

e|Адрес регистрации сотрудника
e|Адрес регистрации
e|Буквенно-числовое значение
e|150
|

e|Адрес проживания сотрудника
e|Адрес проживания
e|Буквенно-числовое значение
e|150
|

s|Воинский учет сотрудника
s|Сводные данные о воинском учете сотрудника
s|категория годности

+ комиссариат

+ ВУС

+ воинское звание
|
|

e|Категория годности
e|Категория годности к военной службе
e|Одна буква и одна цифра
e|2
|

e|Комиссариат
e|Наименование военного комиссариата по месту жительства
e|Буквенно-числовое значение
e|150
|

e|ВУС
e|Военно-учетная специальность
e|6 цифр + (одна буква)
e|7
|

e|Воинское звание
e|Звание военнослужащего или военнообязанного в запасе
e|Буквенно-числовое значение
e|150
|

e|Передвижение по должностям сотрудника
e|Передвижение по должностям сотрудника внутри компании
e|+ 1: многие {пребывание в должности}
|
|

s|Пребывание в должности сотрудника
s|Непрерывное пребывание в должности сотрудником
s|+ должность

+ дата вступления в должность

+ дата перемещения с должности
|
|

e|Дата вступления в должность
e|Дата вступления в должность
e|Дата согласно RFC 3339
|
|

e|Дата перемещения с должности
e|Дата перемещения с должности (перевод, увольнение)
e|Дата согласно RFC 3339
|
|

s|Паспорт сотрудника
s|Сводные данные о паспорте сотрудника
s|идентификатор паспорта

+ дата выдачи

+ организация, выдавшая паспорт

+ номер

+ тип

+ 0: многие {виза сотрудника}
|
|

e|Идентификатор паспорта
e|Уникальный идентификатор документа, назначаемый системой каждому добавленному паспорту
e|Целое
e|10
|

e|Дата выдачи паспорта
e|Дата выдачи паспорта
e|Дата согласно RFC 3339
e|10
|

e|Организация, выдавшая паспорт
e|Название организации, которая выдала данный паспорт
e|Буквенно-числовое значение
e|150
|

e|Номер паспорта
e|Номер паспорта
e|Числовое значение
e|50
|

e|Тип паспорта
e|Тип паспорта, из представленного перечисления
e|Буквенное значение
|
e|внутренний, заграничный, иностранца

s|Разрешение на работу сотрудника
s|Сводные данные о разрешении на работу сотрудника
s|номер разрешения на работу

+ дата начала действия разрешения на работу

+ дата окончания действия разрешения на работу
|
|

e|Дата начала действия разрешения на работу
e|Дата начала действия разрешения на работу
e|Дата согласно RFC 3339
e|10
|

e|Дата окончания действия разрешения на работу
e|Дата окончания действия разрешения на работу
e|Дата согласно RFC 3339
e|10
|

e|Номер разрешения на работу
e|Номер разрешения на работу
e|Числовое значение
|
|

s|Виза сотрудника
s|Сводные данные о визе сотрудника
s|идентификатор

+ дата начала действия

+ дата окончания действия

+ страна, выдавшая визу

+ номер

+ количество въездов
|
|

e|Идентификатор визы
e|Уникальный идентификатор документа, назначаемый системой каждой добавленной визе
e|Целое
e|10
|

e|Дата начала действия визы
e|Дата начала действия визы
e|Дата согласно RFC 3339
e|10
|

e|Дата окончания действия визы
e|Дата окончания действия визы
e|Дата согласно RFC 3339
e|10
|

e|Номер визы
e|Номер визы
e|Числовое значение
e|50
|

e|Страна, выдавшая визу
e|Страна, выдавшая визу
e|Буквенно-числовое значение
e|50
|

e|Количество въездов по визе
e|Количество разрешенных въездов в страну, из представленного перечисления
e|Буквенно-числовое значение
|
e|1, 2, мульти

s|Отпуск сотрудника
s|Сводные данные об отпуске сотрудника
s|идентификатор

+ дата начала

+ дата окончания
|
|

e|Идентификатор отпуска
e|Уникальный идентификатор, назначаемый системой каждому добавленному отпуску
e|Целое
e|10
|

e|Дата начала отпуска
e|Дата начала отпуска
e|Дата согласно RFC 3339
e|10
|

e|Дата окончания отпуска
e|Дата окончания отпуска
e|Дата согласно RFC 3339
e|10
|

s|Скан документа сотрудника
|
s|идентификатор

+ тип документа

+ описание скана

+ дата и время загрузки
|
|

e|Идентификатор скана документа
e|Уникальный идентификатор, назначаемый системой каждому добавленному скану документа сотрудника
e|Целое
e|10
|

e|Тип документа сотрудника
e|Тип документа сотрудника, из представленного перечисления
e|Буквенное значение
|
e|паспорт, ИНН, СНИЛС, трудовой договор, согласие на обработку персональных данных, воинский учет, свидетельство о браке, свидетельство о рождении ребенка, документ об образовании, документ об обучении, инструктаж, разрешение на работу, другое

e|Описание скана документа сотрудника
e|Дополнительная информация, указываемая пользователем
e|Буквенно-числовое значение
|150
|

e|Дата и время загрузки скана документа сотрудника
e|Дата и время загрузки скана документа сотрудника
e|Дата и время согласно RFC 3339
|
|

s|Трудовой договор сотрудника
s|Сводная информация о трудовом договоре сотрудника
s|идентификатор

+ номер

+ тип

+ дата начала действия

+ дата окончания действия
|
|

e|Идентификатор трудового договора
e|Уникальный идентификатор, назначаемый системой каждому добавленному трудовому договору
e|Целое
e|10
|

e|Номер трудового договора
e|Номер трудового договора
e|Буквенно-числовое значение
e|50
|

e|Тип трудового договора
e|Тип трудового договора, из представленного перечисления
e|Буквенное значение
|
e|постоянный, временный

e|Дата начала действия трудового договора
e|Дата начала действия трудового договора
e|Дата согласно RFC 3339
e|10
|

e|Дата окончания действия трудового договора
e|Дата окончания действия трудового договора
e|Дата согласно RFC 3339
e|10
|

s|Отдел компании
s|Сводная информация об отделе компании
s|идентификатор

+ название

+ количество сотрудников

+ количество сотрудников на подборе
|
|

e|Идентификатор отдела
e|Уникальный идентификатор, назначаемый системой каждому добавленному отделу компании
e|Целое
e|10
|

e|Название отдела
e|Название отдела
e|Буквенно-числовое значение
e|150
|

e|Количество сотрудников отдела
e|Количество сотрудников отдела
e|Целое
e|10
|

e|Количество сотрудников на подборе в отделе
e|Количество сотрудников на подборе в отделе
e|Целое
e|10
|

s|Образование сотрудника
s|Сводная информация об образовании сотрудника
s|идентификатор

+ номер документа

+ дата начала

+ дата окончания

+ организация

+ программа
|
|

e|Идентификатор образования
e|Уникальный идентификатор, назначаемый системой каждому добавленному образованию сотрудника
e|Целое
e|10
|

e|Номер документа об образовании
e|Номер документа об образовании сотрудника
e|Буквенно-числовое значение
e|50
|

e|Организация образования
e|Организация образования
e|Буквенно-числовое значение
e|150
|

e|Дата начала образования
e|Дата начала образования
e|Дата согласно RFC 3339
e|10
|

e|Дата окончания образования
e|Дата окончания образования
e|Дата согласно RFC 3339
e|10
|

e|Программа образования
e|Программа образования
e|Буквенно-числовое значение
e|150
|

s|Обучение сотрудника
s|Сводная информация об обучении сотрудника
s|идентификатор

+ номер документа

+ дата начала

+ дата окончания

+ организация

+ программа
|
|

e|Идентификатор обучения
e|Уникальный идентификатор, назначаемый системой каждому добавленному обучению сотрудника
e|Целое
e|10
|

e|Номер документа об обучении
e|Номер документа об обучении
e|Буквенно-числовое значение
e|50
|

e|Организация обучения
e|Организация обучения
e|Буквенно-числовое значение
e|150
|

e|Дата начала обучения
e|Дата начала обучения
e|Дата согласно RFC 3339
e|10
|

e|Дата окончания обучения
e|Дата окончания обучения
e|Дата согласно RFC 3339
e|10
|

e|Программа обучения
e|Программа обучения
e|Буквенно-числовое значение
e|150
|

s|Кандидат
s|Сводная информация о кандидате
s|идентификатор

+ фамилия

+ имя

+ отчество

+ должность

+ электронная почта

+ телефон
|
|

e|Идентификатор кандидата
e|Уникальный идентификатор, назначаемый системой каждому добавленному кандидату
e|Целое
e|10
|

e|Фамилия кандидата
e|Фамилия кандидата
e|Буквенное значение
e|150
|

e|Имя кандидата
e|Имя сотрудника
e|Буквенное значение
e|150
|

e|Отчество кандидата
e|Отчество кандидата
e|Буквенное значение
e|150
|

e|Должность кандидата
e|Должность, на которую рассматривается, кандидат
e|Буквенно-числовое значение
e|150
|

e|Электронная почта кандидата
e|Электронная почта кандидата
e|Буквенно-числовое значение
e|50
|

e|Телефон кандидата
e|Телефон кандидата
e|Числовое значение
e|15
|

e|Логин пользователя
e|Логин (email) для входа в систему
e|Буквенно-числовое значение
e|50
|

e|Пароль пользователя
e|Хэш пароля пользователя
e|Строка base64
e|?
|

e|Ключ смены пароля
e|Уникальный ключ, создаваемый системой при запросе смены пароля и отправляемый на email пользователя
e|Строка base64
e|36
|

|===
