= Пользовательские истории (User stories)

*«Главная страница - Кнопка "Войти"»*

__US1: Как hr-специалист (здесь и далее - #пользователь#) хочу иметь возможность войти в систему для получения доступа к её функциям.__

_US2: Я как пользователь хочу зарегистрироваться на сайте чтобы не потерять данные/пользоваться платформой._

*«Главная страница - Кнопка "Восстановить"»*

_US: Как пользователь хочу иметь возможность восстановить доступ к личному кабинету (картотеке) для дальнейшего использования его функционала._

*Просмотр страницы "Картотека сотрудников", список сотрудников от А до Я*

_US: Как пользователь хочу иметь возможность выводить список всех работников в алфавитном порядке для быстрого визуального поиска нужного мне сотрудника._

*Просмотр страницы "Картотека сотрудников" , список сотрудников по отделам*

_US: Как пользователь хочу иметь возможность увидеть список всех сотрудников по отделам для наглядности._

*Просмотр страницы "Картотека сотрудников", оргструктура детализированная*

_US: Как пользователь хочу иметь возможность видеть структуру своей организации для того, чтобы перейти к списку сотрудников конкретного отдела._

*Просмотр личной карточки сотрудника*

_US: Как пользователь хочу иметь возможность посмотреть все имеющиеся данные о конкретном сотруднике чтобы получить необходимую мне информацию о нем._

*Особые профессиональные навыки*

_US: Как пользователь хочу иметь возможность списка с флажками чтобы наглядно указать навыки/быстрее заполнить анкету._

*Знание иностранных языков*

_US: Как пользователь хочу иметь возможность списка чтобы быстрее указать владение языками._

*Информация об образовании*

_US: Как пользователь хочу иметь возможность добавления блоков чтобы иметь возможность указать несколько сведений об образовании._

*Период обучения*

_US: Как пользователь хочу иметь добавления блоков, чтобы иметь возможность оповещения об окончании обучения сотрудника._

*Опыт работы*

_US: Как пользователь хочу иметь возможность добавления блоков, чтобы иметь возможность указать несколько мест работы._
