// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

type bearerAuthScopesType string

const (
	BearerAuthScopes bearerAuthScopesType = "bearerAuth.Scopes"
)

// Defines values for ContractType.
const (
	Permanent    ContractType = "permanent"
	SelfEmployed ContractType = "self_employed"
	Temporary    ContractType = "temporary"
)

// Defines values for Gender.
const (
	Female Gender = "female"
	Male   Gender = "male"
)

// Defines values for PassportType.
const (
	External   PassportType = "external"
	Foreigners PassportType = "foreigners"
	Internal   PassportType = "internal"
)

// Defines values for ScanType.
const (
	ScanTypeBabyBirth              ScanType = "baby_birth"
	ScanTypeBriefing               ScanType = "briefing"
	ScanTypeContract               ScanType = "contract"
	ScanTypeEducation              ScanType = "education"
	ScanTypeInsurance              ScanType = "insurance"
	ScanTypeMarriage               ScanType = "marriage"
	ScanTypeMilitary               ScanType = "military"
	ScanTypeOther                  ScanType = "other"
	ScanTypePassport               ScanType = "passport"
	ScanTypePersonalDataProcessing ScanType = "personal_data_processing"
	ScanTypeTaxpayer               ScanType = "taxpayer"
	ScanTypeTraining               ScanType = "training"
	ScanTypeWorkPermit             ScanType = "work_permit"
)

// Defines values for VisaNumberEntries.
const (
	Mult VisaNumberEntries = "mult"
	N1   VisaNumberEntries = "1"
	N2   VisaNumberEntries = "2"
)

// Defines values for WorkingModel.
const (
	Hybrid   WorkingModel = "hybrid"
	InOffice WorkingModel = "in-office"
	Remote   WorkingModel = "remote"
)

// Defines values for ListUsersParamsSortBy.
const (
	ListUsersParamsSortByAlphabet   ListUsersParamsSortBy = "alphabet"
	ListUsersParamsSortByDepartment ListUsersParamsSortBy = "department"
)

// AddContractRequest defines model for AddContractRequest.
type AddContractRequest struct {
	DateFrom openapi_types.Date  `json:"date_from"`
	DateTo   *openapi_types.Date `json:"date_to,omitempty"`
	Number   string              `json:"number"`
	Type     ContractType        `json:"type"`
}

// AddEducationRequest defines model for AddEducationRequest.
type AddEducationRequest struct {
	// DateFrom date of commencement of studies
	DateFrom openapi_types.Date `json:"date_from"`

	// DateTo date of graduation
	DateTo            openapi_types.Date `json:"date_to"`
	IssuedInstitution string             `json:"issued_institution"`
	Number            string             `json:"number"`
	Program           string             `json:"program"`
}

// AddPassportRequest defines model for AddPassportRequest.
type AddPassportRequest struct {
	IssuedBy   string             `json:"issued_by"`
	IssuedDate openapi_types.Date `json:"issued_date"`
	Number     string             `json:"number"`
	Type       PassportType       `json:"type"`
}

// AddTrainingRequest defines model for AddTrainingRequest.
type AddTrainingRequest struct {
	// Cost cost per person, in their minor unit form
	Cost uint64 `json:"cost"`

	// DateFrom start date of training
	DateFrom openapi_types.Date `json:"date_from"`

	// DateTo end date of training
	DateTo            openapi_types.Date `json:"date_to"`
	IssuedInstitution string             `json:"issued_institution"`
	Program           string             `json:"program"`
}

// AddUserRequest defines model for AddUserRequest.
type AddUserRequest struct {
	DateOfBirth         openapi_types.Date  `json:"date_of_birth"`
	DepartmentID        uint64              `json:"department_id"`
	Email               openapi_types.Email `json:"email"`
	FirstName           string              `json:"first_name"`
	ForeignLanguages    []string            `json:"foreign_languages,omitempty"`
	Gender              Gender              `json:"gender"`
	Grade               string              `json:"grade"`
	Insurance           Insurance           `json:"insurance"`
	LastName            string              `json:"last_name"`
	MiddleName          string              `json:"middle_name"`
	Military            *Military           `json:"military,omitempty"`
	Nationality         string              `json:"nationality"`
	PhoneNumbers        PhoneNumbers        `json:"phone_numbers"`
	PlaceOfBirth        string              `json:"place_of_birth"`
	PositionID          uint64              `json:"position_id"`
	RegistrationAddress string              `json:"registration_address"`
	ResidentialAddress  string              `json:"residential_address"`
	Taxpayer            Taxpayer            `json:"taxpayer"`
	WorkPermit          *WorkPermit         `json:"work_permit,omitempty"`
	WorkingModel        *WorkingModel       `json:"working_model,omitempty"`
}

// AddVacationRequest defines model for AddVacationRequest.
type AddVacationRequest struct {
	DateFrom openapi_types.Date `json:"date_from"`
	DateTo   openapi_types.Date `json:"date_to"`
}

// AddVisaRequest defines model for AddVisaRequest.
type AddVisaRequest struct {
	IssuedState   string             `json:"issued_state"`
	Number        string             `json:"number"`
	NumberEntries VisaNumberEntries  `json:"number_entries"`
	ValidFrom     openapi_types.Date `json:"valid_from"`
	ValidTo       openapi_types.Date `json:"valid_to"`
}

// ChangePasswordRequest defines model for ChangePasswordRequest.
type ChangePasswordRequest struct {
	// Key a special key sent to the employee’s email
	Key string `json:"key"`

	// Password a new employee password
	Password string `json:"password"`
}

// Contract defines model for Contract.
type Contract struct {
	DateFrom openapi_types.Date  `json:"date_from"`
	DateTo   *openapi_types.Date `json:"date_to,omitempty"`
	HasScan  *bool               `json:"has_scan,omitempty"`
	ID       uint64              `json:"id"`
	Number   string              `json:"number"`
	Type     ContractType        `json:"type"`
}

// ContractType defines model for ContractType.
type ContractType string

// Department defines model for Department.
type Department struct {
	ID   uint64 `json:"id"`
	Name string `json:"name"`

	// RecruitedUsersNumber number of recruited employees
	RecruitedUsersNumber int `json:"recruited_users_number"`

	// UsersNumber current number of working employees
	UsersNumber int `json:"users_number"`
}

// Education defines model for Education.
type Education struct {
	// DateFrom date of commencement of studies
	DateFrom openapi_types.Date `json:"date_from"`

	// DateTo date of graduation
	DateTo            openapi_types.Date `json:"date_to"`
	HasScan           *bool              `json:"has_scan,omitempty"`
	ID                uint64             `json:"id"`
	IssuedInstitution string             `json:"issued_institution"`
	Number            string             `json:"number"`
	Program           string             `json:"program"`
}

// Error defines model for Error.
type Error struct {
	Code    *int   `json:"code,omitempty"`
	Message string `json:"message"`
}

// ExpandedPassport defines model for ExpandedPassport.
type ExpandedPassport struct {
	Passport
	Visas []Visa `json:"visas"`
}

// Gender defines model for Gender.
type Gender string

// GetContractResponse defines model for GetContractResponse.
type GetContractResponse = Contract

// GetEducationResponse defines model for GetEducationResponse.
type GetEducationResponse = Education

// GetExpandedPassportResponse defines model for GetExpandedPassportResponse.
type GetExpandedPassportResponse = ExpandedPassport

// GetExpandedUserResponse defines model for GetExpandedUserResponse.
type GetExpandedUserResponse struct {
	GetUserResponse
	Contracts  []Contract         `json:"contracts"`
	Educations []Education        `json:"educations"`
	Passports  []ExpandedPassport `json:"passports"`
	Trainings  []Training         `json:"trainings"`
	Vacations  []Vacation         `json:"vacations"`
}

// GetPassportResponse defines model for GetPassportResponse.
type GetPassportResponse = Passport

// GetTrainingResponse defines model for GetTrainingResponse.
type GetTrainingResponse = Training

// GetUserResponse defines model for GetUserResponse.
type GetUserResponse struct {
	DateOfBirth            openapi_types.Date     `json:"date_of_birth"`
	DepartmentID           uint64                 `json:"department_id"`
	Email                  openapi_types.Email    `json:"email"`
	Finance                *UserFinance           `json:"finance,omitempty"`
	FirstName              string                 `json:"first_name"`
	ForeignLanguages       []string               `json:"foreign_languages,omitempty"`
	Gender                 Gender                 `json:"gender"`
	Grade                  string                 `json:"grade"`
	ID                     uint64                 `json:"id,omitempty"`
	Insurance              Insurance              `json:"insurance"`
	LastName               string                 `json:"last_name"`
	MiddleName             string                 `json:"middle_name"`
	Military               *Military              `json:"military,omitempty"`
	Nationality            string                 `json:"nationality"`
	PersonalDataProcessing PersonalDataProcessing `json:"personal_data_processing"`
	PhoneNumbers           PhoneNumbers           `json:"phone_numbers"`
	PlaceOfBirth           string                 `json:"place_of_birth"`
	PositionID             uint64                 `json:"position_id"`
	PositionTrack          PositionTrack          `json:"position_track"`
	RegistrationAddress    string                 `json:"registration_address"`
	ResidentialAddress     string                 `json:"residential_address"`
	Taxpayer               Taxpayer               `json:"taxpayer"`
	WorkPermit             *WorkPermit            `json:"work_permit,omitempty"`
	WorkingModel           *WorkingModel          `json:"working_model,omitempty"`
}

// GetVacationResponse defines model for GetVacationResponse.
type GetVacationResponse = Vacation

// GetVisaResponse defines model for GetVisaResponse.
type GetVisaResponse = Visa

// InitChangePasswordRequest defines model for InitChangePasswordRequest.
type InitChangePasswordRequest struct {
	// Login employee login (email)
	Login openapi_types.Email `json:"login"`
}

// Insurance defines model for Insurance.
type Insurance struct {
	HasScan *bool  `json:"has_scan,omitempty"`
	Number  string `json:"number"`
}

// ListContractsResponse defines model for ListContractsResponse.
type ListContractsResponse = []Contract

// ListEducationsResponse defines model for ListEducationsResponse.
type ListEducationsResponse = []Education

// ListPassportsResponse defines model for ListPassportsResponse.
type ListPassportsResponse = []Passport

// ListScansResponse defines model for ListScansResponse.
type ListScansResponse = []Scan

// ListTrainingsResponse defines model for ListTrainingsResponse.
type ListTrainingsResponse = []Training

// ListUsersItem defines model for ListUsersItem.
type ListUsersItem struct {
	Department   string              `json:"department"`
	Email        openapi_types.Email `json:"email"`
	FirstName    string              `json:"first_name"`
	ID           uint64              `json:"id"`
	LastName     string              `json:"last_name"`
	MiddleName   string              `json:"middle_name"`
	PhoneNumbers PhoneNumbers        `json:"phone_numbers"`
	Position     string              `json:"position"`
}

// ListUsersResponse defines model for ListUsersResponse.
type ListUsersResponse struct {
	// CurrentPage current page number (based on current limit parameter)
	CurrentPage int `json:"current_page"`

	// TotalPages total pages count (based on current limit parameter)
	TotalPages int `json:"total_pages"`

	// TotalUsers total employee count in company
	TotalUsers int             `json:"total_users"`
	Users      []ListUsersItem `json:"users"`
}

// ListVacationsResponse defines model for ListVacationsResponse.
type ListVacationsResponse = []Vacation

// ListVisasResponse defines model for ListVisasResponse.
type ListVisasResponse = []Visa

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	// Login employee login (email)
	Login openapi_types.Email `json:"login"`

	// Password employee password
	Password string `json:"password"`
}

// Military defines model for Military.
type Military struct {
	Category    string `json:"category"`
	Comissariat string `json:"comissariat"`
	HasScan     *bool  `json:"has_scan,omitempty"`
	Rank        string `json:"rank"`
	Speciality  string `json:"speciality"`
}

// Passport defines model for Passport.
type Passport struct {
	HasScan    bool               `json:"has_scan"`
	ID         uint64             `json:"id"`
	IssuedBy   string             `json:"issued_by"`
	IssuedDate openapi_types.Date `json:"issued_date"`
	Number     string             `json:"number"`
	Type       PassportType       `json:"type"`
	VisasCount uint               `json:"visas_count"`
}

// PassportType defines model for PassportType.
type PassportType string

// PatchContractRequest defines model for PatchContractRequest.
type PatchContractRequest struct {
	DateFrom *openapi_types.Date `json:"date_from,omitempty"`
	DateTo   *openapi_types.Date `json:"date_to,omitempty"`
	Number   *string             `json:"number,omitempty"`
	Type     *ContractType       `json:"type,omitempty"`
}

// PatchEducationRequest defines model for PatchEducationRequest.
type PatchEducationRequest struct {
	// DateFrom date of commencement of studies
	DateFrom *openapi_types.Date `json:"date_from,omitempty"`

	// DateTo date of graduation
	DateTo            *openapi_types.Date `json:"date_to,omitempty"`
	IssuedInstitution *string             `json:"issued_institution,omitempty"`
	Number            *string             `json:"number,omitempty"`
	Program           *string             `json:"program,omitempty"`
}

// PatchPassportRequest defines model for PatchPassportRequest.
type PatchPassportRequest struct {
	IssuedBy   *string             `json:"issued_by,omitempty"`
	IssuedDate *openapi_types.Date `json:"issued_date,omitempty"`
	Number     *string             `json:"number,omitempty"`
	Type       *PassportType       `json:"type,omitempty"`
}

// PatchTrainingRequest defines model for PatchTrainingRequest.
type PatchTrainingRequest struct {
	// Cost cost per person, in their minor unit form
	Cost *int64 `json:"cost,omitempty"`

	// DateFrom start date of training
	DateFrom *openapi_types.Date `json:"date_from,omitempty"`

	// DateTo end date of training
	DateTo            *openapi_types.Date `json:"date_to,omitempty"`
	IssuedInstitution *string             `json:"issued_institution,omitempty"`
	Program           *string             `json:"program,omitempty"`
}

// PatchUserRequest defines model for PatchUserRequest.
type PatchUserRequest struct {
	DateOfBirth         *openapi_types.Date  `json:"date_of_birth,omitempty"`
	DepartmentID        *uint64              `json:"department_id,omitempty"`
	Email               *openapi_types.Email `json:"email,omitempty"`
	FirstName           *string              `json:"first_name,omitempty"`
	ForeignLanguages    []string             `json:"foreign_languages,omitempty"`
	Gender              *Gender              `json:"gender,omitempty"`
	Grade               *string              `json:"grade,omitempty"`
	Insurance           *Insurance           `json:"insurance,omitempty"`
	LastName            *string              `json:"last_name,omitempty"`
	MiddleName          *string              `json:"middle_name,omitempty"`
	Military            *Military            `json:"military,omitempty"`
	Nationality         *string              `json:"nationality,omitempty"`
	PhoneNumbers        PhoneNumbers         `json:"phone_numbers,omitempty"`
	PlaceOfBirth        *string              `json:"place_of_birth,omitempty"`
	PositionID          *uint64              `json:"position_id,omitempty"`
	PositionTrack       PositionTrack        `json:"position_track,omitempty"`
	RegistrationAddress *string              `json:"registration_address,omitempty"`
	ResidentialAddress  *string              `json:"residential_address,omitempty"`
	Taxpayer            *Taxpayer            `json:"taxpayer,omitempty"`
	WorkPermit          *WorkPermit          `json:"work_permit,omitempty"`
	WorkingModel        *WorkingModel        `json:"working_model,omitempty"`
}

// PatchVacationRequest defines model for PatchVacationRequest.
type PatchVacationRequest struct {
	DateFrom *openapi_types.Date `json:"date_from,omitempty"`
	DateTo   *openapi_types.Date `json:"date_to,omitempty"`
}

// PatchVisaRequest defines model for PatchVisaRequest.
type PatchVisaRequest struct {
	IssuedState   *string             `json:"issued_state,omitempty"`
	Number        *string             `json:"number,omitempty"`
	NumberEntries *VisaNumberEntries  `json:"number_entries,omitempty"`
	ValidFrom     *openapi_types.Date `json:"valid_from,omitempty"`
	ValidTo       *openapi_types.Date `json:"valid_to,omitempty"`
}

// PersonalDataProcessing defines model for PersonalDataProcessing.
type PersonalDataProcessing struct {
	HasScan bool `json:"has_scan"`
}

type PhoneNumber string

// PhoneNumbers defines model for PhoneNumbers.
type PhoneNumbers map[string]PhoneNumber

// PositionTrack defines model for PositionTrack.
type PositionTrack = []PositionTrackItem

// PositionTrackItem defines model for PositionTrackItem.
type PositionTrackItem struct {
	DateFrom   openapi_types.Date  `json:"date_from"`
	DateTo     *openapi_types.Date `json:"date_to,omitempty"`
	PositionID uint64              `json:"position_id"`
}

// PutContractRequest defines model for PutContractRequest.
type PutContractRequest struct {
	DateFrom openapi_types.Date  `json:"date_from"`
	DateTo   *openapi_types.Date `json:"date_to,omitempty"`
	Number   string              `json:"number"`
	Type     ContractType        `json:"type"`
}

// PutEducationRequest defines model for PutEducationRequest.
type PutEducationRequest struct {
	// DateFrom date of commencement of studies
	DateFrom openapi_types.Date `json:"date_from"`

	// DateTo date of graduation
	DateTo            openapi_types.Date `json:"date_to"`
	IssuedInstitution string             `json:"issued_institution"`
	Number            string             `json:"number"`
	Program           string             `json:"program"`
}

// PutPassportRequest defines model for PutPassportRequest.
type PutPassportRequest struct {
	IssuedBy   string             `json:"issued_by"`
	IssuedDate openapi_types.Date `json:"issued_date"`
	Number     string             `json:"number"`
	Type       PassportType       `json:"type"`
}

// PutTrainingRequest defines model for PutTrainingRequest.
type PutTrainingRequest struct {
	// Cost cost per person, in their minor unit form
	Cost uint64 `json:"cost"`

	// DateFrom start date of training
	DateFrom openapi_types.Date `json:"date_from"`

	// DateTo end date of training
	DateTo            openapi_types.Date `json:"date_to"`
	IssuedInstitution string             `json:"issued_institution"`
	Program           string             `json:"program"`
}

// PutUserRequest defines model for PutUserRequest.
type PutUserRequest struct {
	DateOfBirth         openapi_types.Date  `json:"date_of_birth"`
	DepartmentID        uint64              `json:"department_id"`
	Email               openapi_types.Email `json:"email"`
	FirstName           string              `json:"first_name"`
	ForeignLanguages    []string            `json:"foreign_languages,omitempty"`
	Gender              Gender              `json:"gender"`
	Grade               string              `json:"grade"`
	Insurance           Insurance           `json:"insurance"`
	LastName            string              `json:"last_name"`
	MiddleName          string              `json:"middle_name"`
	Military            *Military           `json:"military,omitempty"`
	Nationality         string              `json:"nationality"`
	PhoneNumbers        PhoneNumbers        `json:"phone_numbers"`
	PlaceOfBirth        string              `json:"place_of_birth"`
	PositionID          uint64              `json:"position_id"`
	PositionTrack       PositionTrack       `json:"position_track"`
	RegistrationAddress string              `json:"registration_address"`
	ResidentialAddress  string              `json:"residential_address"`
	Taxpayer            Taxpayer            `json:"taxpayer"`
	WorkPermit          *WorkPermit         `json:"work_permit,omitempty"`
	WorkingModel        *WorkingModel       `json:"working_model,omitempty"`
}

// PutVacationRequest defines model for PutVacationRequest.
type PutVacationRequest struct {
	DateFrom openapi_types.Date `json:"date_from"`
	DateTo   openapi_types.Date `json:"date_to"`
}

// PutVisaRequest defines model for PutVisaRequest.
type PutVisaRequest struct {
	IssuedState   string             `json:"issued_state"`
	Number        string             `json:"number"`
	NumberEntries VisaNumberEntries  `json:"number_entries"`
	ValidFrom     openapi_types.Date `json:"valid_from"`
	ValidTo       openapi_types.Date `json:"valid_to"`
}

// Scan defines model for Scan.
type Scan struct {
	Description *string `json:"description,omitempty"`

	// DocumentID document ID (if necessary), passport ID for passport scan, for example
	DocumentID *uint64  `json:"document_id,omitempty"`
	ID         uint64   `json:"id"`
	Type       ScanType `json:"type"`

	// UploadAt an upload date-time as defined by full-date - RFC3339
	UploadAt time.Time `json:"upload_at"`
}

// ScanType defines model for ScanType.
type ScanType string

// Taxpayer defines model for Taxpayer.
type Taxpayer struct {
	HasScan *bool  `json:"has_scan,omitempty"`
	Number  string `json:"number"`
}

// Training defines model for Training.
type Training struct {
	// Cost cost per person, in their minor unit form
	Cost uint64 `json:"cost"`

	// DateFrom start date of training
	DateFrom openapi_types.Date `json:"date_from"`

	// DateTo end date of training
	DateTo            openapi_types.Date `json:"date_to"`
	HasScan           *bool              `json:"has_scan,omitempty"`
	ID                uint64             `json:"id"`
	IssuedInstitution string             `json:"issued_institution"`
	Program           string             `json:"program"`
}

// UserFinance defines model for UserFinance.
type UserFinance struct {
	// IncomeTax tax paid to revenue service per month, in their minor unit form
	IncomeTax *int64 `json:"income_tax,omitempty"`

	// Salary gross salary per month, in their minor unit form
	Salary *int64 `json:"salary,omitempty"`

	// SocialSecurityTax tax paid to social services per month, in their minor unit form
	SocialSecurityTax *int64 `json:"social_security_tax,omitempty"`
}

// Vacation defines model for Vacation.
type Vacation struct {
	DateFrom openapi_types.Date `json:"date_from"`
	DateTo   openapi_types.Date `json:"date_to"`
	ID       uint64             `json:"id"`
}

// Visa defines model for Visa.
type Visa struct {
	HasScan       bool               `json:"has_scan"`
	ID            uint64             `json:"id"`
	IssuedState   string             `json:"issued_state"`
	Number        string             `json:"number"`
	NumberEntries VisaNumberEntries  `json:"number_entries"`
	ValidFrom     openapi_types.Date `json:"valid_from"`
	ValidTo       openapi_types.Date `json:"valid_to"`
}

// VisaNumberEntries defines model for VisaNumberEntries.
type VisaNumberEntries string

// WorkPermit defines model for WorkPermit.
type WorkPermit struct {
	HasScan   *bool              `json:"has_scan,omitempty"`
	Number    string             `json:"number"`
	ValidFrom openapi_types.Date `json:"valid_from"`
	ValidTo   openapi_types.Date `json:"valid_to"`
}

// WorkingModel defines model for WorkingModel.
type WorkingModel string

// CheckKeyParams defines parameters for CheckKey.
type CheckKeyParams struct {
	// Key a special key sent to the employee’s email
	Key string `form:"key" json:"key"`
}

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {
	// Limit maximum number of results to return
	Limit *uint `form:"limit,omitempty" json:"limit,omitempty"`

	// Query query to find by
	Query *string `form:"query,omitempty" json:"query,omitempty"`

	// Page page number with results to return
	Page *uint `form:"page,omitempty" json:"page,omitempty"`

	// SortBy type of sort result by
	SortBy *ListUsersParamsSortBy `form:"sort_by,omitempty" json:"sort_by,omitempty"`
}

// ListUsersParamsSortBy defines parameters for ListUsers.
type ListUsersParamsSortBy string

// GetUserParams defines parameters for GetUser.
type GetUserParams struct {
	// Expanded whether to return detailed data on passports, contracts, vacations, etc. along with user data (default - no)
	Expanded *bool `form:"expanded,omitempty" json:"expanded,omitempty"`
}

// GetPassportParams defines parameters for GetPassport.
type GetPassportParams struct {
	// Expanded whether to return visas along with user passport data (default - no)
	Expanded *bool `form:"expanded,omitempty" json:"expanded,omitempty"`
}

// UploadScanMultipartBody defines parameters for UploadScan.
type UploadScanMultipartBody struct {
	Description *string            `json:"description,omitempty"`
	DocumentID  *uint64            `json:"document_id,omitempty"`
	FileName    openapi_types.File `json:"fileName"`
	Type        ScanType           `json:"type"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// ChangePasswordJSONRequestBody defines body for ChangePassword for application/json ContentType.
type ChangePasswordJSONRequestBody = ChangePasswordRequest

// InitChangePasswordJSONRequestBody defines body for InitChangePassword for application/json ContentType.
type InitChangePasswordJSONRequestBody = InitChangePasswordRequest

// AddUserJSONRequestBody defines body for AddUser for application/json ContentType.
type AddUserJSONRequestBody = AddUserRequest

// PatchUserJSONRequestBody defines body for PatchUser for application/json ContentType.
type PatchUserJSONRequestBody = PatchUserRequest

// PutUserJSONRequestBody defines body for PutUser for application/json ContentType.
type PutUserJSONRequestBody = PutUserRequest

// AddContractJSONRequestBody defines body for AddContract for application/json ContentType.
type AddContractJSONRequestBody = AddContractRequest

// PatchContractJSONRequestBody defines body for PatchContract for application/json ContentType.
type PatchContractJSONRequestBody = PatchContractRequest

// PutContractJSONRequestBody defines body for PutContract for application/json ContentType.
type PutContractJSONRequestBody = PutContractRequest

// AddEducationJSONRequestBody defines body for AddEducation for application/json ContentType.
type AddEducationJSONRequestBody = AddEducationRequest

// PatchEducationJSONRequestBody defines body for PatchEducation for application/json ContentType.
type PatchEducationJSONRequestBody = PatchEducationRequest

// PutEducationJSONRequestBody defines body for PutEducation for application/json ContentType.
type PutEducationJSONRequestBody = PutEducationRequest

// AddPassportJSONRequestBody defines body for AddPassport for application/json ContentType.
type AddPassportJSONRequestBody = AddPassportRequest

// PatchPassportJSONRequestBody defines body for PatchPassport for application/json ContentType.
type PatchPassportJSONRequestBody = PatchPassportRequest

// PutPassportJSONRequestBody defines body for PutPassport for application/json ContentType.
type PutPassportJSONRequestBody = PutPassportRequest

// AddVisaJSONRequestBody defines body for AddVisa for application/json ContentType.
type AddVisaJSONRequestBody = AddVisaRequest

// PatchVisaJSONRequestBody defines body for PatchVisa for application/json ContentType.
type PatchVisaJSONRequestBody = PatchVisaRequest

// PutVisaJSONRequestBody defines body for PutVisa for application/json ContentType.
type PutVisaJSONRequestBody = PutVisaRequest

// UploadScanMultipartRequestBody defines body for UploadScan for multipart/form-data ContentType.
type UploadScanMultipartRequestBody UploadScanMultipartBody

// AddTrainingJSONRequestBody defines body for AddTraining for application/json ContentType.
type AddTrainingJSONRequestBody = AddTrainingRequest

// PatchTrainingJSONRequestBody defines body for PatchTraining for application/json ContentType.
type PatchTrainingJSONRequestBody = PatchTrainingRequest

// PutTrainingJSONRequestBody defines body for PutTraining for application/json ContentType.
type PutTrainingJSONRequestBody = PutTrainingRequest

// AddVacationJSONRequestBody defines body for AddVacation for application/json ContentType.
type AddVacationJSONRequestBody = AddVacationRequest

// PatchVacationJSONRequestBody defines body for PatchVacation for application/json ContentType.
type PatchVacationJSONRequestBody = PatchVacationRequest

// PutVacationJSONRequestBody defines body for PutVacation for application/json ContentType.
type PutVacationJSONRequestBody = PutVacationRequest
